### ISSUE TITLE
rgb2colorblind repository

### ISSUE THREAD

**Issue by heberleh** [daijro/peacock#1]
Hi @Daijro, I couldn't find other way to contact you, so I'm writing here.
Your repository [rgb2colorblind](https://github.com/daijro/rgb2colorblind) is labeled as GPL. Can you explain how you can do that if  it is based on a noncommercial software? Thank you

**Comment by daijro** [comment]
Hello, thank you for bringing attention to this. GPL-3.0 was attributed by mistake
